# Example services configuration
# Uncomment and modify as needed

http:
  routers: 
    idm:
      entryPoints:
        - "https"
      rule: "Host(`idm.{{env "IDM_DOMAIN"}}`)"
      middlewares:
        - public
      tls: {}
      service: lan_traefik
    service1:
      entryPoints:
        - "https"
      rule: "Host(`{{env "LAN_SERVICE1"}}`.{{env "PUBLIC_DOMAIN"}}`)"
      middlewares:
        - public
      tls: {}
      service: lan_traefik

  services:
    lan_traefik:
      loadBalancer:
        servers:
          - url: "https://192.168.145.2:443"
        passHostHeader: true
