http:
  # serversTransports:
  #   insecureTransport:
  #     insecureSkipVerify: true

  routers: 
    idm:
      entryPoints:
        - "websecure"
      rule: "Host(`{{env "IDM_DOMAIN"}}`)"
      middlewares:
        - public
      tls: {}
      service: lan_traefik
    service1:
      entryPoints:
        - "websecure"
      rule: "Host(`{{env "LAN_SERVICE1"}}.{{env "PUBLIC_DOMAIN"}}`)"
      middlewares:
        - public
      tls: {}
      service: lan_traefik
    service2:
      entryPoints:
        - "websecure"
      rule: "Host(`{{env "LAN_SERVICE2"}}.{{env "PUBLIC_DOMAIN"}}`)"
      middlewares:
        - public
      tls: {}
      service: lan_traefik
    

  services:
    lan_traefik:
      loadBalancer:
        servers:
          - url: "https://10.1.20.15:443"
        passHostHeader: true
        #serversTransport: insecureTransport
